fix opts set interval and when fetchTime is undefined (not null)
devvmh/redux-crud-store pull request #58
Opened 2017-08-05 00:08 UTC by shengnian

This PR fix opts config interval for `recent()` and when the `fetchTime === undefined` issue.

2017-08-05 00:14 UTC, devvmh commented
Hi

I'll aim to review this on Sunday

2017-08-05 00:17 UTC, shengnian commented
@devvmh thanks a lot.

2017-08-07 15:12 UTC, devvmh requested changes

2017-08-07 15:12 UTC, devvmh commented on src/selectors.js
> +  if (!fetchTime) return false
What's the purpose of this change?

2017-08-07 15:12 UTC, devvmh commented on src/selectors.js
> +  const interval = (opts && opts.interval) || 10 * 60 * 1000 // ten minutes
I'd rather this function throw an error if opts is undefined. Are you able to revert this? If not, can you explain why it's necessary?

2017-08-07 15:12 UTC, devvmh commented on src/selectors.js
> +      selection = selectCollection(model, crud, params, opts)
👍

2017-09-09 17:48 UTC, devvmh commented
@shengnian ping!

2018-03-17 17:29 UTC, devvmh commented
Closing; feel free to re-open if you update the request

2018-03-17 17:29 UTC, closed without merging